modLoader="javafml"
loaderVersion="[46,)"
license="LGPL v2.1"
[[mods]]
modId="traderefresh"
version="${file.jarVersion}" #mandatory
displayName="Trade Refresh" #mandatory
logoFile="traderefresh.png" #optional
credits="Thanks to the Technical Minecraft community" #optional
authors="lcy0x1 and LightLand team" #optional
description='''
'''
[[dependencies.traderefresh]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.traderefresh]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"